import KBAside from '../../../components/kb/KBAside'
import KBNote from '../../../components/kb/KBNote'
import { KBH2, KBP } from '../../../components/kb/KBHeading'

export default function ContractTestingTools() {
  return (
    <>
      <KBP>
        Contract testing addresses a specific integration problem that neither unit tests
        nor end-to-end tests solve reliably: verifying that two independently developed
        services remain compatible as each evolves. Pact is the dominant open-source tool
        for consumer-driven contract testing, supporting a workflow in which the consuming
        service defines its expectations and the providing service verifies it can meet them,
        without requiring both services to run at the same time.
      </KBP>

      <KBH2 id="how-pact-works">How Pact works</KBH2>

      <KBP>
        <a href="https://pact.io" target="_blank" rel="noopener noreferrer" className="text-link hover:underline">Pact</a> models
        the relationship between a consumer and a provider as a contract, a document that
        describes the HTTP interactions the consumer expects to make. The consumer's test
        suite runs against a Pact mock provider, records the interactions it makes and
        writes them to a JSON contract file. The provider's test suite then replays those
        recorded interactions against the real provider and verifies that its responses
        match what the contract specifies.
      </KBP>

      <KBP>
        This approach decouples the two services entirely during testing. The consumer tests
        do not require a running provider, and the provider tests do not require a running
        consumer. Each service can be verified independently in its own CI pipeline, and
        a contract failure surfaces the incompatibility at the point of change, before either
        service is deployed. In a microservices environment where spinning up the full
        dependency graph for integration testing is slow or fragile, this is a significant
        practical advantage.
      </KBP>

      <KBH2 id="the-pact-workflow">The Pact workflow</KBH2>

      <KBP>
        The consumer writes tests that describe what it expects from the provider: the
        request path, method, headers and body, and the expected response status code,
        headers and body shape. Pact generates and records these as interactions in the
        contract file. The consumer publishes the contract to a Pact Broker, a central
        repository for contracts, and the provider retrieves it from the broker and runs
        its verification tests.
      </KBP>

      <KBP>
        Pact supports matching rules that make contracts more flexible without making them
        loose. Rather than asserting that a field has an exact value, a contract can assert
        that a field is present and is a string, that a number is within a range or that an
        array contains at least one element of a given type. This prevents contracts from
        breaking on every data change while still detecting structural incompatibilities
        that would cause real failures.
      </KBP>

      <KBP>
        Pact is available in JavaScript and TypeScript, Java, Python, Ruby, Go, .NET, Scala
        and PHP, allowing consumer and provider to be implemented in different languages
        while sharing the same contract format. The underlying Pact specification is
        language-agnostic, so a contract generated by a JavaScript consumer can be verified
        by a Java provider without any translation.
      </KBP>

      <KBH2 id="pact-broker">Pact Broker and PactFlow</KBH2>

      <KBP>
        The open-source <a href="https://docs.pact.io/pact_broker" target="_blank" rel="noopener noreferrer" className="text-link hover:underline">Pact Broker</a> stores
        and serves contracts between teams. It tracks which version of a consumer contract
        has been verified by which version of a provider, enabling the can-i-deploy tool
        to answer the question of whether a given version of a service is safe to deploy
        given the current state of its dependencies. This turns the Pact Broker into a
        deployment gate rather than just a file store.
      </KBP>

      <KBP>
        <a href="https://pactflow.io" target="_blank" rel="noopener noreferrer" className="text-link hover:underline">PactFlow</a> is
        the commercial hosted version of the Pact Broker, operated by SmartBear. The
        open-source Pact libraries and specification remain community-maintained. It adds a web UI, user management, bi-directional contract
        testing support for teams that cannot modify the provider and deeper CI integration.
        Teams running Pact at scale or in regulated environments typically use PactFlow
        rather than self-hosting the open-source broker.
      </KBP>

      <KBAside label="Consumer-driven contracts and team autonomy" variant="gold">
        The consumer-driven model shifts the definition of a valid API from the provider
        to its consumers. A provider can make any change that does not break an existing
        consumer contract and deploy with confidence. This gives teams genuine independence:
        a breaking change is detected before deployment rather than discovered through
        a production incident or a failed integration test that requires both services to
        be running. In organisations where multiple teams share a service, the Pact Broker
        provides visibility into which teams' contracts would be affected by a proposed
        provider change.
      </KBAside>

      <KBNote variant="blue">
        Pact is not a substitute for integration testing in all cases. It verifies that
        a provider can handle the interactions a consumer expects, but it does not test
        the provider's internal logic, database interactions or behaviour under load. It
        is most valuable when the cost of running full integration environments is high
        and when the consumer and provider are developed and deployed independently by
        different teams. For monolithic applications or tightly coupled services that are
        always deployed together, the overhead of maintaining contracts may not be justified.
      </KBNote>
    </>
  )
}
