import KBAside from '../../../components/kb/KBAside'
import KBNote from '../../../components/kb/KBNote'
import { KBH2, KBP } from '../../../components/kb/KBHeading'

export default function SecurityTestingTools() {
  return (
    <>
      <KBP>
        Security testing tools identify vulnerabilities in web applications by probing
        their behaviour in ways that a normal user or functional test would not. They look
        for weaknesses in authentication, input validation, session management and
        access control that could allow an attacker to compromise the application or its
        data. OWASP ZAP and Burp Suite are the two most widely used tools in this category,
        occupying different points on the spectrum from open-source automation to professional
        manual security testing.
      </KBP>

      <KBH2 id="owasp-zap">OWASP ZAP</KBH2>

      <KBP>
        <a href="https://www.zaproxy.org" target="_blank" rel="noopener noreferrer" className="text-link hover:underline">OWASP ZAP</a> (Zed
        Attack Proxy) is an open-source security testing tool maintained by the Open Web
        Application Security Project. It operates as an intercepting proxy, sitting between
        the browser or test client and the application, observing all traffic and analysing
        it for security issues. Passive scanning observes traffic generated by normal browsing
        or test execution and flags potential issues without sending any additional requests.
        Active scanning sends crafted payloads to the application to probe for specific
        vulnerability classes including SQL injection, cross-site scripting and misconfigured
        headers.
      </KBP>

      <KBP>
        ZAP's API and command-line interface make it well suited to integration into CI
        pipelines. The official Docker image allows it to be run as a pipeline step against
        a deployed environment, and ZAP's automation framework supports configuring scan
        rules, authentication and scope without a graphical interface. The GitHub Actions
        integration can add a basic security scan to a workflow with minimal configuration.
      </KBP>

      <KBP>
        ZAP also supports API scanning using an OpenAPI, Swagger or GraphQL definition to
        enumerate endpoints and construct test requests automatically, without requiring a
        browser session. This makes it applicable to API-only services that have no
        rendered UI.
      </KBP>

      <KBH2 id="burp-suite">Burp Suite</KBH2>

      <KBP>
        <a href="https://portswigger.net/burp" target="_blank" rel="noopener noreferrer" className="text-link hover:underline">Burp Suite</a> is
        developed by PortSwigger and is the most widely used tool in professional web
        application security testing. It is available in a free Community edition and a
        paid Professional edition. Both editions include an intercepting proxy, an HTTP
        history viewer, a repeater for manually modifying and replaying requests and a
        decoder for working with encoded values. The Professional edition adds Burp Scanner,
        an automated vulnerability scanner, and Burp Intruder at full speed for fuzzing
        and brute-force tasks.
      </KBP>

      <KBP>
        Burp's Repeater tool is central to manual security testing workflows. A tester
        captures a request, modifies parameters, headers or body content and replays it
        to observe the application's response. This iterative process is how injection
        vulnerabilities, authentication bypasses and access control flaws are explored
        and confirmed. Burp Collaborator, available in Professional, provides an out-of-band
        interaction server for detecting blind vulnerabilities such as server-side request
        forgery where the application does not reflect the vulnerability in its response.
      </KBP>

      <KBP>
        Burp Suite's extension ecosystem, available through the BApp Store, adds additional
        scanning checks, custom reporting and integrations with other security tools.
        Many organisations use Burp as the primary tool for penetration tests and security
        audits, supplementing its automated scanner with manual exploration using the
        proxy and repeater.
      </KBP>

      <KBAside label="Which tool to use" variant="gold">
        OWASP ZAP and Burp Suite are not directly competing in most contexts. ZAP is better
        suited to automated security scanning in CI pipelines, particularly for teams that
        want to add baseline security checks without a dedicated security specialist. Burp
        Suite Professional is the right tool for security professionals conducting structured
        penetration tests or vulnerability assessments where manual exploration and
        precise request manipulation are required. Teams serious about application security
        often use both: ZAP for continuous automated coverage and Burp for periodic
        in-depth assessments.
      </KBAside>

      <KBNote variant="warning">
        Security testing tools must only be run against systems you are authorised to test.
        Running an active scan against a system without explicit permission is illegal in
        most jurisdictions regardless of whether the tester owns an account on that system.
        Always confirm the scope of authorisation in writing before running any automated
        security scan, restrict testing to environments designated for that purpose and
        ensure that scan traffic cannot reach production systems unintentionally.
      </KBNote>
    </>
  )
}
